global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api"
    static_configs:
      - targets: ["api:3000"]

  - job_name: "ws"
    static_configs:
      - targets: ["ws:4000"]

  - job_name: "worker"
    static_configs:
      - targets: ["worker:9464"]
